# -*- coding: utf-8 -*-
"""Maximum_marginal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9wt62dY_K5U75f-Xol_nXiD0zxDbKK2
"""

!pip install langchain chromadb faiss-cpu openai tiktoken langchain_openai langchain-community wikipedia langchain_huggingface

from langchain_core.documents import Document
from langchain_huggingface.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

docs  = [
    Document(page_content="Langchain helps developer to develop LLM applications easily"),
    Document(page_content="Chroma is a vector database that is optimized for the LLM baed search"),
    Document(page_content="Embeeeding convert the text into the high dimentional vector"),
    Document(page_content="OpenAI models provides the high end dimentional embeding"),
    Document(page_content="MMR helps to extract the diverse results when doing the similarity search"),
    Document(page_content="langchain supports the Chroma,Faiss ,pinecone and more "),
    Document(page_content="Langchain make it easy to work with LLM")
]

embeeding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

vector_store = FAISS.from_documents(docs,embeeding_model)
vector_store

retriver =  vector_store.as_retriever(search_type='mmr' , kwargs={"k":0 ,"lamda_mult": 0.5}) # when
# values is 1 it behave same as the similarity search so it is kept between the 0-1

query = "what is langchain?"

result = retriver.invoke(query)

result

