# -*- coding: utf-8 -*-
"""vector_reteriver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mg5fFZJc5yugpSLGGiZPEqoBC6uUWseH
"""

!pip install langchain chromadb faiss-cpu openai tiktoken langchain_openai langchain-community wikipedia langchain_huggingface

from langchain_community.vectorstores import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document

docs  = [
    Document(page_content="Langchain helps developer to develop LLM applications easily"),
    Document(page_content="Chroma is a vector database that is optimized for the LLM baed search"),
    Document(page_content="Embeeeding convert the text into the high dimentional vector"),
    Document(page_content="OpenAI models provides the high end dimentional embeding")
]

embeeing_model = HuggingFaceEmbeddings(model = 'sentence-transformers/all-MiniLM-L6-v2')
vector_store = Chroma.from_documents(documents = docs , embedding=embeeing_model , collection_name = "my_collection" )

retriver = vector_store.as_retriever(search_kwargs={"k":1})

retriver

query = "For what puropose the chroma is used for?"
resluts = retriver.invoke(query)
resluts

print(resluts[0].page_content)

