# -*- coding: utf-8 -*-
"""wikipidia_retriver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154Ta3tQaSPDfbXh1JtMxxtucu0x3SYh6
"""

!pip install langchain chromadb faiss-cpu openai tiktoken langchain_openai langchain-community wikipedia

from langchain_community.retrievers import WikipediaRetriever

retriver = WikipediaRetriever(top_k_results=2 , lang='en')

query = "Role of quaid e Azam in the creation of Pakistan"
docs = retriver.invoke(query)
docs

print(docs[0].metadata)







